### ISSUE TITLE
Can't find integration "Airbnk lock" after installing

### ISSUE THREAD

**Issue by StonyHartman** [rospogrigio/airbnk_cloud#3]
I installed via HACS and there is a folder "airbnk_cloud" in custom_components. But ther is no airbnk lock in the dropdown list of all the integrations. I have restarted Home assistant a few times and also tried to install the master version. In HACS I can see the "Airbnk lock cloud-based integration" but there is no configuration button. Can you tell me what I am doing wrong?

**Comment by rospogrigio** [comment]
When you see the dropdown list, try a hard refresh (should be shift+F5, or Ctrl+Shift+R maybe, check your browser), then retry and it should appear. You can also try to clear your browser cache. Please confirm if it works, bye...

**Comment by StonyHartman** [comment]
Great! It worked.

Sorry for that didn’t thought of the cache problem.

 

Van: rospogrigio ***@***.***> 
Verzonden: woensdag 6 april 2022 13:55
Aan: rospogrigio/airbnk_cloud ***@***.***>
CC: StonyHartman ***@***.***>; Author ***@***.***>
Onderwerp: Re: [rospogrigio/airbnk_cloud] Can't find integration "Airbnk lock" after installing (Issue #3)

 

When you see the dropdown list, try a hard refresh (should be shift+F5, or Ctrl+Shift+R maybe, check your browser), then retry and it should appear. You can also try to clear your browser cache. Please confirm if it works, bye...
