### ISSUE TITLE
battery status

### ISSUE THREAD

**Issue by giltabibian** [rospogrigio/airbnk_cloud#4]
is it possible to get the lock & fingerprint status?

**Comment by rospogrigio** [comment]
Not with the cloud calls, since they don't return those values.
You need to purchase an ESP32 board and switch to the MQTT integration: https://github.com/rospogrigio/airbnk_mqtt 
Bye!

**Comment by giltabibian** [comment]
@rospogrigio thanks for the quick answer!
Can you recommend on esp32 module to buy that suits these needs?
Or if you have a guide/video that explains about it.

**Comment by rospogrigio** [comment]
Any ESP32 device should do the job, I own one like this and it's working fine: https://www.amazon.it/AZDelivery-NodeMCU-Development-Arduino-gratuito/dp/B071P98VTG/ref=asc_df_B071P98VTG/
You can find some documentation in the Integration page, it should explain how to use it quite easily.

**Comment by giltabibian** [comment]
Sure. Thanks!
